#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

cookbook 'apt'

cookbook 'apache2'

cookbook 'mysql'
cookbook 'php'
cookbook 'postgresql'
cookbook 'mongodb'
# ,      :git => 'https://github.com/edelight/chef-mongodb.git'
cookbook 'imagemagick'


cookbook 'rvm',
#    :git => 'https://github.com/fnichol/chef-rvm.git'
   :git => 'https://github.com/gpsnail/chef-rvm.git'

cookbook 'nodejs',
   :git => 'https://github.com/mdxp/nodejs-cookbook.git'

cookbook 'nodejs',
   :git => 'https://github.com/mdxp/nodejs-cookbook.git'

cookbook 'composer',
	:git => 'https://github.com/gpsnail/chef-composer.git'


# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'

